CXX		= g++ -std=c++11

01: 01.cpp
	$(CXX) $? -o $@.out

02: 02.cpp
	$(CXX) $? -o $@.out

03: 03.cpp
	$(CXX) $? -o $@.out

04: 04.cpp
	$(CXX) $? -o $@.out

05: 05.cpp
	$(CXX) $? -o $@.out

06: 06.cpp
	$(CXX) $? -o $@.out

clear:
	rm *.out