CC = clang++ -std=c++11

01: 01.cpp
	$(CC) 01.cpp -o 01.out

03: 03.cpp
	$(CC) 03.cpp -o 03.out

11: 11.cpp
	$(CC) 11.cpp -o 11.out

13: 13.cpp
	$(CC) 13.cpp -o 13.out

14: 14.cpp
	$(CC) 14.cpp -o 14.out

clean:
	rm *.out
